---
name: 01-ALZ-Dev-Platform-Connectivity CI
on:
  pull_request:
    branches:
      - main
    paths:
      - 'connectivity/**'
  workflow_dispatch:
  

jobs:
  validate_and_plan:
    uses: ALZ-Lab/atlz-dev/.github/workflows/ci-template.yaml@main
    name: 'CI'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
