---
name: 01-Platform-Connectivity CI
on:
  pull_request:
    branches:
      - main
    paths:
      - "connectivity/**"
  workflow_dispatch:

jobs:
  validate_and_plan:
    uses: ALZ-Lab/atlz-dev/.github/workflows/ci-template.yaml@main
    name: "CI"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      WORKING_DIR: "./connectivity"
#      environment: "atlz-dev-plan"
#      subscription_id: ${{ vars.CONNECTIVITY_SUBSCRIPTION_ID }}
#    secrets:
#      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
#      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
#      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
#      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
#      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
